server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/admin/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/api/vehicle/**
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/booking/**
        - id: revive-app
          uri: lb://REVIVE-APP
          predicates:
            - Path=/api/revive/**

  main:
    web-application-type: reactive

#eureka service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


#spring:
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

#  datasource:
#    url: jdbc:mysql://localhost:3306/revive
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver